### ISSUE TITLE
关于梁小霞同志的相关信息纠正

### ISSUE THREAD

**Issue by HiPeach** [MobiusBeta/20191208#1]
梁小霞同志的身份应为**党员**
以下内容来源于[百度百科相关词条](https://baike.baidu.com/item/梁小霞/24672997)
> 根据梁小霞同志生前意愿，2020年6月自治区党委批准追认其为[中国共产党党员](https://baike.baidu.com/item/中国共产党党员/6301426)
2020年6月9日，[广西壮族自治区党委](https://baike.baidu.com/item/中国共产党广西壮族自治区委员会/12695914)常委会召开会议，同意追授梁小霞同志为自治区先进工作者，追认梁小霞同志为中共党员

**Comment by MobiusBeta** [comment]
**谢谢您的反馈！**
梁小霞同志的政治面貌信息已在“23w01a Revise the list & update copyright year”提交中订正为党员。
